force-app/main/default/objects/Application__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Retry Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Last_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt__c</fullName>
    <label>Last Attempt</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CandidateSyncQueueable.cls
public class CandidateSyncQueueable implements Queueable, Database.AllowsCallouts {

    private Id recordId;

    public CandidateSyncQueueable(Id recId){
        this.recordId = recId;
    }

    public void execute(QueueableContext context){

        System.debug('Queueable Running');

        Application__c app = [
            SELECT Id, Name
            FROM Application__c
            WHERE Id = :recordId
        ];

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Recruitment_API/posts');
        req.setMethod('POST');
        req.setHeader('Content-Type','application/json');

        req.setBody('{"name":"' + app.Name + '"}');

        Http http = new Http();
        HttpResponse res = http.send(req);

        app.Last_Attempt__c = System.now();

        if(res.getStatusCode() == 200 || res.getStatusCode() == 201){

            Map<String, Object> responseMap = 
                (Map<String, Object>) JSON.deserializeUntyped(res.getBody());

            if(responseMap.containsKey('id')){
                app.External_Candidate_ID__c = 
                    String.valueOf(responseMap.get('id'));
            }

            app.Integration_Status__c = 'Sent';

        } else {
            app.Integration_Status__c = 'Failed';
            app.Error_Message__c = res.getBody();
        }

        // 🔥 MUST
        update app;
    }
}