force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Minimum_CGPA__c.field-meta.xml
<CustomField>
    <fullName>Minimum_CGPA__c</fullName>
    <label>Minimum CGPA</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApplicationController.cls
public with sharing class ApplicationController {

    // 🔹 Get Jobs
    @AuraEnabled(cacheable=true)
    public static List<Job__c> getEligibleJobs() {
        return [
            SELECT Id, Name, Company__c, Location__c, Closing_Date__c, Minimum_CGPA__c
            FROM Job__c
            ORDER BY CreatedDate DESC
        ];
    }

    // 🔹 Apply Job
    @AuraEnabled
    public static String submitApplication(Id studentId, Id jobId) {

        // Prevent duplicate
        List<Application__c> existing = [
            SELECT Id FROM Application__c
            WHERE Student__c = :studentId
            AND Job__c = :jobId
        ];

        if (!existing.isEmpty()) {
            return 'You already applied for this job';
        }

        Application__c app = new Application__c();
        app.Student__c = studentId;
        app.Job__c = jobId;
        app.Status__c = 'Applied';
        app.Application_Date__c = Date.today();

        insert app;

        return 'Application submitted successfully';
    }

    // 🔹 My Applications
    @AuraEnabled(cacheable=true)
    public static List<Application__c> getMyApplications(Id studentId) {
        return [
            SELECT Id,
                   Status__c,
                   Application_Date__c,
                   Job__r.Name,
                   Job__r.Company__c
            FROM Application__c
            WHERE Student__c = :studentId
            ORDER BY CreatedDate DESC
        ];
    }
}